"""
Define constants
"""

# Screen setup
SCREEN_WIDTH = 1366
SCREEN_HEIGHT = 768
SCREEN_TITLE = "jam game"

# Sprite scaling
CHARACTER_SCALING = 0.20
TILE_SCALING = 0.5
COIN_SCALING = 1

# Player movement
PLAYER_SPEED = 10
GRAVITY = 3
JUMP_SPEED = 40

# Viewport setup
LEFT_VIEWPORT_MARGIN = SCREEN_WIDTH/2
RIGHT_VIEWPORT_MARGIN = SCREEN_WIDTH/2
BOTTOM_VIEWPORT_MARGIN = 50
TOP_VIEWPORT_MARGIN = 100
